---
- name: Lesson 4 Project 1 - User and Group management
  hosts: managed
  become: true

  vars:
    users:
      - name: devops
        groups: wheel
        shell: /bin/bash
      - name: webadmin
        groups: apache
        shell: /bin/bash

  tasks:
    - name: Ensure groups exist
      ansible.builtin.group:
        name: "{{ item.groups }}"
        state: present
      loop: "{{ users }}"

    - name: Ensure users exist
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        shell: "{{ item.shell }}"
        state: present
      loop: "{{ users }}"

    - name: Verify users exist
      ansible.builtin.command: getent passwd {{ item.name }}
      loop: "{{ users }}"
      register: verify_results
      ignore_errors: true

    - name: Display verification results
      ansible.builtin.debug:
        var: verify_results.results

